version: '3'

services:

  app:
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenetwork
    volumes:
      - ./node:/user/src/app
    tty: true
    container_name: app
    depends_on:
      - db

  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=nodedb
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=root
    networks:
      - nodenetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: vitorcarra/nginx_nodejs:prod
    container_name: nginx
    networks:
      - nodenetwork
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  nodenetwork:
    driver: bridge